### ISSUE TITLE
Helper: ID generating methods

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#1]
We need an easy way to create URIs for objects like Manifests and Canvases

 * Config has default ID generation method
 * It makes ID optional if supplied it is override otherwise it creates a default. 
 * Set base_uri

**Comment by glenrobson** [comment]
This would be a helper class in https://github.com/iiif-prezi/iiif-prezi3/tree/main/iiif_prezi3/helpers

Should:
 * Encode special characters (UTF-8) 
 * Warn if it contains # as it could be a fragment selector

**Comment by glenrobson** [comment]
Something like: https://github.com/linked-art/crom/blob/master/cromulent/model.py#L288-L314

**Comment by azaroth42** [comment]
I don't know how to do this with pydantic *and* as a Helper that manipulates the class hierarchy.

Pydantic expects a minimally valid record to be passed as keywords into the __init__ function of BaseModel.  We can inject some further code into base.Base.__init__ ... but it needs to manipulate the call to BaseModel's constructor, rather than running after the instance has been built.

**Comment by azaroth42** [comment]
Update - I stopped trying to monkeypatch the class in, and instead just set a property on the skeleton generated classes. Doesn't follow the same pattern as the other helpers, but it doesn't need to, as it doesn't expose functionality on instances.

Comments welcome (here) on the approach taken:
* https://github.com/iiif-prezi/iiif-prezi3/blob/id_generator/iiif_prezi3/base.py#L6-L13 
* https://github.com/iiif-prezi/iiif-prezi3/blob/id_generator/iiif_prezi3/helpers/auto_fields.py

Thanks! (@glenrobson @mbennett-uoe @zimeon)

**Comment by glenrobson** [comment]
Discussed on the call (25th Feb) and are happy with the approach. We think you could do something like:

```

class NewDefault(object):
    def generate_defaults(self, what, **kw):
        if not 'id' in kw:
            return {'id': "http://glen.com/" + reposerviceGetNewID()}


Manifest.defaults.append(NewDefault)

m = Manifest(label="My Manifest")
```

to set your own default id generator.

**Comment by azaroth42** [comment]
Assuming that `reposerviceGetNewID()` is visible to the function, then yes :)
