### ISSUE TITLE
Investigate `--strict-nullable` option in datamodel-code-generator

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#143]
At the moment we have some fields that are required, such as `type` coming through as `Optional` with a default set.

It looks like datamodel-code-generator has an argument that can make these fields required while preserving the default. See https://github.com/koxudaxi/datamodel-code-generator/issues/757

Although we have a constrained string for type, I think it should still work - so we should investigate generating the skeleton with this and seeing if everything still works!

**Comment by glenrobson** [comment]
Discussed in call 13th Jan. Would be useful to investigate.

**Comment by digitaldogsbody** [comment]
This worked perfectly first time, `type` no longer gets the `Optional[]` annotation and everything still works :grinning:
