### ISSUE TITLE
Update datamodel-code-generator to version 0.17.0

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#156]
A couple of the issues we reported have now been fixed so we should see if we can remove the workarounds with generating the schema.  

This one is to do with the lang string issues: (and we could close https://github.com/iiif-prezi/iiif-prezi3/issues/23) (datamodel v 0.15.0)

https://github.com/koxudaxi/datamodel-code-generator/issues/696

This one is to do with the `@id` and `@type` issues we've seen in services (datamodel v 0.14.1):

https://github.com/koxudaxi/datamodel-code-generator/issues/917

we originally discussed this issue [here](https://github.com/iiif-prezi/iiif-prezi3/pull/89).

**Comment by glenrobson** [comment]
Looks like https://github.com/koxudaxi/datamodel-code-generator/issues/917 doesn't fix our issues as it adds a prefix before the underscore e.g. `field_id` we want to  remove the `_` from the beginning.

**Comment by koxudaxi** [comment]
@glenrobson 
OK. I will think about how to resolve the problem.

**Comment by koxudaxi** [comment]
@glenrobson  
I have released the new version as `0.16.1`
Could you please `--remove-special-field-name-prefix` as CLI option?
Thank you very much!!

**Comment by glenrobson** [comment]
Thanks @koxudaxi we will run a test!

**Comment by digitaldogsbody** [comment]
That looks like it has fixed the issue with the `_id` and `_type` fields :)

**Comment by digitaldogsbody** [comment]
The other bug with `LngString` seems to persist, sadly

**Comment by koxudaxi** [comment]
@digitaldogsbody Thank you for testing it.

>The other bug with LngString seems to persist, sadly

Could you please explain the problem?

**Comment by digitaldogsbody** [comment]
@koxudaxi Thanks so much for the responsive fixes - it makes a big difference to our project :relaxed: 

The other issue is the one that @giacomomarchioro opened here: https://github.com/koxudaxi/datamodel-code-generator/issues/696

In the `types` section of our schema, we have:
```json
"lngString": {
            "title": "Language string, must have a language and value must be an array.",
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z-][a-zA-Z-]*$": {
                    "type": "array",
                    "items": { "type": "string"}
                },
                "^none$": {
                    "type": "array",
                    "items": { "type": "string"}
                }
            },
            "additionalProperties": false
        },
```

`datamodel-code-generator` (0.16.1) is creating:
```python
class LngString(Base):
    pass

    class Config:
        extra = Extra.forbid
```

We are expecting something like:
```python
class LngString(Base):
    __root__: Dict[str, List[str]]

    class Config:
        extra = Extra.forbid
```

**Comment by digitaldogsbody** [comment]
The whole schema file is here: https://github.com/IIIF/presentation-validator/blob/2f9f7e4ec5f671ebcdf8b2eef76cae2a7d50f26b/schema/iiif_3_0.json

And the command we are using is: `datamodel-codegen --input iiif_3_0.json --input-file-type jsonschema --use-default --remove-special-field-name-prefix --strict-nullable --base-class .base.Base --output skeleton.py`

**Comment by koxudaxi** [comment]
@digitaldogsbody 
Thank you for explaining the detail 
I tried the command with the master branch version.
The problem is solved with the latest code.
I will release a new version within a few days.
```bash
$ pip install git+https://github.com/koxudaxi/datamodel-code-generator.git
```
```python
# generated by datamodel-codegen:
#   filename:  iiif_3_0.json
#   timestamp: 2023-01-28T09:41:10+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, Extra, Field, PositiveFloat, PositiveInt, constr
...

class LngString(Base):
    __root__: Union[
        Dict[constr(regex=r'^[a-zA-Z-][a-zA-Z-]*$'), List[str]],
        Dict[constr(regex=r'^none$'), List[str]],
    ] = Field(
        ..., title='Language string, must have a language and value must be an array.'
    )

...
```

**Comment by digitaldogsbody** [comment]
Amazing, thank you so much!

**Comment by digitaldogsbody** [comment]
datamodel-code-generator 0.17.0 is out (https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.17.0) which contains the above fix - so we should update to that and test that it's resolved the LngString issue
