### ISSUE TITLE
How to use the library for simple use cases

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#18]
Like setting the id and label.

See the testNewManifest method:

https://github.com/iiif-prezi/iiif-prezi3/blob/08320320f66e53496a923ad08b1f586ee8655e99/tests/test_basic.py#L25

**Comment by rbturnbull** [comment]
This test looks like a helpful example. Thanks!

**Comment by glenrobson** [comment]
ID class comes in here from the schema:

https://github.com/IIIF/presentation-validator/blob/90197c88d8676c652cf475909bf34ab689fb6ea0/schema/iiif_3_0.json#L5

**Comment by glenrobson** [comment]
The label issue is probably related to https://github.com/iiif-prezi/iiif-prezi3/issues/11

**Comment by azaroth42** [comment]
A nasty workaround:

In base.py:
```
class Base(BaseModel):

    def __getattribute__(self, prop):
        val = super(Base, self).__getattribute__(prop)
        if hasattr(val, '__root__'):
            return str(val.__root__)
        else:
            return val
```

```
>>> from iiif_prezi3 import Manifest, Canvas
>>> m = Manifest(id="http://example.org/foo", type="Manifest", label={"en":"foo"})
>>> m.id
'http://example.org/foo'
```

Which should work for all of the things which have a __root__, like ViewingDirection, Rights, and so on

**Comment by glenrobson** [comment]
That does seem to fix the tests...

**Comment by glenrobson** [comment]
This seems to be resolved now. On to lang Strings. Id can now be manipulated like:

```
manifest = Manifest(id='http://iiif.example.org/prezi/Manifest/0', type='Manifest', label={'en': 'label'})
        self.assertEqual(manifest.id, 'http://iiif.example.org/prezi/Manifest/0', "Unexpected Manifest id ")

        manifest.id = 'http://iiif.example.org/prezi/Manifest/new'

        self.assertEqual(manifest.id, 'http://iiif.example.org/prezi/Manifest/new', "Expected manifest id to change")

        # invalid id:
        with self.assertRaises(ValidationError):
            manifest.id = 'invalid_id'
```
