### ISSUE TITLE
Can't create SVG Selectors for Annotations

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#180]
You cannot create a target for an `Annotation` with a `SpecificResource` that has a string value for `selector` (see https://iiif.io/api/cookbook/recipe/0261-non-rectangular-commenting/ for an example)

### Expected behaviour:

`SpecificResource` would allow the `SvgSelector` construct

### Observed behaviour:

The selector attribute gets omitted completely when the JSON is printed

### Potential bug location(s):

https://github.com/iiif-prezi/iiif-prezi3/blob/main/iiif_prezi3/skeleton.py#L97-L103

`SpecificResource` currently requires either `AnyUrl` or an `AnnoSelectorItem` class, neither of which has the `value` property required by SvgSelector

### Any other comments:

It looks like this construct was added to the schema (https://github.com/IIIF/presentation-validator/commit/6a3a9010d32240a327940c4bd3b78dd9b32887c7) but after the last skeleton regeneration - so hopefully a regeneration should fix things pretty easily.

**Comment by jpadfield** [comment]
Hi, sorry just checking, has there been any progress with this one?

**Comment by digitaldogsbody** [comment]
@glenrobson did you get a chance to look at the RangeRef removal?

I am happy to put in a temporary hotfix for this using the skeleton modifier tool to allow the skeleton to be regenerated, which will add the SvgSelector and resolve Joe's issue.

**Comment by glenrobson** [comment]
I did and unfortunately it broke my automated tests. I think it would be better to move to this version of the schema: https://github.com/IIIF/presentation-validator/pull/155 but it requires some work as it moves to if / then / else rather than oneOfs. I'm part way through writing some code to replace if / then / else with oneOfs for the conversion.

**Comment by digitaldogsbody** [comment]
I have done the above and as of [Release 1.2.1](https://github.com/iiif-prezi/iiif-prezi3/releases/tag/1.2.1) support for `SvgSelector` is now functional :)
