### ISSUE TITLE
add_items helper not available on AccompanyingCanvas

### ISSUE THREAD

**Issue by markpbaggett** [iiif-prezi/iiif-prezi3#199]
While working on a solution for `recipe_0014`, I noticed that the `add_item()` helper is not available on `AccompanyingCanvas`. If you wanted to use the `AccompanyingCanvas` class and not just `Canvas`, it would be useful to have `add_item()` available here.

### Expected behaviour:
`add_item()` is available to AccompanyingCanvas

### Observed behaviour:
An exception is thrown when `add_item()` is used here.

### Potential bug location(s):
https://github.com/iiif-prezi/iiif-prezi3/blob/aeed7b663d7e53674320c1b313085b16271b8c49/iiif_prezi3/helpers/add_item.py#L2

**Comment by glenrobson** [comment]
Done in #200
