### ISSUE TITLE
Import problem with helpers

### ISSUE THREAD

**Issue by rettinghaus** [iiif-prezi/iiif-prezi3#21]
When I try to `import iiif_prezi3` I get the error:

> ModuleNotFoundError: No module named 'iiif_prezi3.helpers'

Python 3.9.9 on macOS 12.1 (M1)

**Comment by rettinghaus** [comment]
Only happened with version 0.2.1 from PyPI. Manual install with 0.2.2 works.

**Comment by digitaldogsbody** [comment]
There was an error with the setup.py and the subpackages didn't get installed correctly - sorry about that! It should also be resolved with the PyPi v0.2.2 install.
