### ISSUE TITLE
Working with language strings

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#23]
I've been looking at language strings particularly with labels e.g.:

```
manifest = Manifest(id='http://iiif.example.org/prezi/Manifest/0', type='Manifest', label={'en': 'label'})

print (manifest.label)
```
The problem is the label is empty. This is due to the [LngString class](https://github.com/iiif-prezi/iiif-prezi3/blob/83af14b72c5525935da5f85e01d181bb1d17fce5/iiif_prezi3/skeleton.py#L62) in the skeleton only containing `pass`.

The relevant part of the schema is:

```
"lngString": {
      "title": "Language string, must have a language and value must be an array.",
      "type": "object",
      "patternProperties": {
                "^[a-zA-Z-][a-zA-Z-]*$": {
               "type": "array",
               "items": { "type": "string"}
            },
            "^none$": {
                "type": "array",
                "items": { "type": "string"}
            }
      },
     "additionalProperties": false
},
```

from [IIIF Schema#L11](https://github.com/IIIF/presentation-validator/blob/1590faee5ae45c95f0dbd76e8b2461e2034ed5af/schema/iiif_3_0.json#L11) and it seems pydantic is struggling with patternProperties and how to convert them into python.

Relevant discussions on pydantics:
 * [JSON Schema patternProperties with Pydantic](https://github.com/samuelcolvin/pydantic/issues/1809)
 * [Support for dynamic fields equivalent to patternProperties in JSON Schema](https://github.com/samuelcolvin/pydantic/discussions/3303)

Example lngStrings include:

```
# single language:
{
   'en': 'label'
}

# multiple languages: 
{
   'en': 'label',
   'cy': 'Welsh Label'
}
```

**Comment by glenrobson** [comment]
We think this should work with pydantic:

```
{
    “type”: “object”
    "propertyNames": {
            "pattern": "^[a-zA-Z-][a-zA-Z-]*$"
      }
    “additionalProperties”: {
        “Type”: “array”,
        “Items”: {  “type”:”string” }    
     }
}

```

We are going create a small example and create an issue with pydantic.

**Comment by giacomomarchioro** [comment]
It seems that replacing  [LngString](https://github.com/iiif-prezi/iiif-prezi3/blob/83af14b72c5525935da5f85e01d181bb1d17fce5/iiif_prezi3/skeleton.py#L62) with:
```
class LngString(Base):
    __root__: Dict[str, List[str]]
```
It works as expected.

I have opened an issue in https://github.com/koxudaxi/datamodel-code-generator/issues/696.

**Comment by digitaldogsbody** [comment]
I will see if it's viable to monkeypatch this fix

**Comment by digitaldogsbody** [comment]
So far attempts at monkeypatching this have failed because of class inheritance - as we are patching in the helper classes as parents of the schema objects, anything they set (in this case `__root__`) is overridden by the value set in the schema object class.

**Comment by glenrobson** [comment]
Decided on the call to edit the skeleton document until this is fixed in pydantic.

**Comment by digitaldogsbody** [comment]
Skeleton edited - I will leave this issue open because it would still be better to find a sustainable fix that doesn't involve editing the skeleton file every time
