### ISSUE TITLE
Add Item

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#37]
## Description

This helper takes a reference to an appropriate object (e.g for a Collection, it would accept a Collection or a Manifest) and adds it to the end of the `items` property

## Function name / Parameters / Return

Function name: `.add_item(item)`

Parameters: `item` - the Prezi3 objetc to be added

Returns: `None`

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [x] Collection
- [x] Manifest
- [x] Canvas
- [x] Range
- [ ] AnnotationCollection
- [x] AnnotationPage
- [ ] Annotation
- [ ] Content Resource - Image
- [ ] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

## Considerations

Different objects will have different acceptable inputs (i.e you can't add a Manifest to a Canvas object's `items`), so this should be validated by the helper code.

**Comment by glenrobson** [comment]
For collection be aware of:

https://github.com/iiif-prezi/iiif-prezi3/blob/main/iiif_prezi3/helpers/collection_add_methods.py

It would be useful if a user can use this method for a collection and pass in a full Manifest and the method should convert it into a reference. 

Main use for other classes is to add the item and return the reference to the one that is added into the class:
```
self.items.append(manifestref)
return manifestref
```

AnnotationPage -> annotationCollection is always a reference

**Comment by digitaldogsbody** [comment]
Considerations:

- Adding Manifest to a Collection **must** add a reference rather than embedding the object
- Allow Pydantic's error handling to deal with invalid assignments (e.g manifest -> canvas items)
- After adding item (using `items.append(<x>)`), use `object.items = object.items` to force Pydantic to revalidate

**Comment by glenrobson** [comment]
Discussed in meeting all done.
