### ISSUE TITLE
Add Metadata

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#38]
## Description

This helper adds key/value pairs to the `metadata` property of a Prezi3 object

## Function name / Parameters / Return

Function name: `.add_metadata(label, value)`

Parameters:
  - `label` - the key to be added the `metadata` property
  - `value` - the value(s) for the key, either a string or an array of strings

Returns: `None`

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [x] Collection
- [x] Manifest
- [x] Canvas
- [x] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [ ] Content Resource - Image
- [ ] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

**Comment by azaroth42** [comment]
The metadata structure is called `KeyValueString` in the schema, which is what this function should create.

For the auto-language feature, see:  https://github.com/iiif-prezi/iiif-prezi3/blob/main/iiif_prezi3/helpers/auto_fields.py 

e.g.
```
>>> from iiif_prezi3 import KeyValueString
>>> kv = KeyValueString(label="label", value="value")
>>> kv
KeyValueString(label=LngString(__root__={'none': ['label']}), value=LngString(__root__={'none': ['value']}))
```

**Comment by azaroth42** [comment]
Do we want a similar function to work for `requiredStatement`? https://iiif.io/api/presentation/3.0/#requiredstatement
