### ISSUE TITLE
Make Manifest

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#42]
## Description

This helper will create a new `Manifest` object, add it **by reference** to the `items` property, and return it

## Function name / Parameters / Return

Function name: `make_manifest()`

Parameters: None

Returns: A `Manifest` object

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [x] Collection
- [ ] Manifest
- [ ] Canvas
- [ ] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [ ] Content Resource - Image
- [ ] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

## Considerations

Manifests must not be embedded inline in a Collection (https://iiif.io/api/presentation/3.0/#51-collection) and therefore this helper must also create a `ManifestReference` and add _that_ to the `items` property of the `Collection` object calling this helper.

**Comment by glenrobson** [comment]
Should add optional parameters of ID but also use the id generating code. 

Label would need to be required as a parameter.

**Comment by glenrobson** [comment]
Potentially only a name change for this method:

https://github.com/iiif-prezi/iiif-prezi3/blob/main/iiif_prezi3/helpers/collection_add_methods.py
