### ISSUE TITLE
Set placeholder canvas

### ISSUE THREAD

**Issue by giacomomarchioro** [iiif-prezi/iiif-prezi3#48]
## Description

It adds a [placeholder canvas](https://iiif.io/api/presentation/3.0/#accompanyingcanvas) to a IIIF object.

## Function name / Parameters / Return

Function name: `.set_placeholder_canvas()`

Parameters: `canvas`

Returns: `canvas` object

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [X] Collection
- [X] Manifest
- [X] Canvas
- [X] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [ ] Content Resource - Image
- [ ] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

## Considerations
Note that in the description is written that the object is a special Canvas that: 

> [The object must not have the placeholderCanvas property, nor the accompanyingCanvas property.](https://iiif.io/api/presentation/3.0/#placeholdercanvas)

But below is also written: 

> *A Canvas that is the value of a placeholderCanvas or accompanyingCanvas property may not have either of those properties itself.

In case the first is the recommendation true we should create a Canvas class that does not have this method.

**Comment by glenrobson** [comment]
We looked at this and without the check to see if the canvas contains other placeholder canvases then its a property setter which we won't need.
