### ISSUE TITLE
Set HWD from file

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#55]
## Description
Introspect a file and set the height, width, and duration properties of a Canvas or Content Resource object, allowing nulls

## Function name / Parameters / Return

Function name: `.set_hwd_from_file(file)`

Parameters: `file` - the file path or file object to introspect

Returns: `None`

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [ ] Collection
- [ ] Manifest
- [x] Canvas
- [ ] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [x] Content Resource - Image
- [x] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

## Considerations

The helper should be able to work with either a file path or an already open file object, so type checking on the parameter will be required.
This helper will introduce new dependencies - probably Pillow for Images and ??? for Audio and Video resources. Please discuss in the ticket or Slack before adding.

For Canvas objects, if `height` is present, then `width` must also be set, and vice-versa (https://iiif.io/api/presentation/3.0/#height / https://iiif.io/api/presentation/3.0/#width), Therefore the helper must be type aware, and raise an error if one is set without the other when the target is a Canvas object

**Comment by digitaldogsbody** [comment]
See also #9 for some discussion about approaches

**Comment by digitaldogsbody** [comment]
It occurs to me that this helper _could_ call the Set HWD helper #(54) once it has established the values, to minimise code duplication a little. This is something we could add after if we wanted, so not a hard requirement for the hackathon.

**Comment by glenrobson** [comment]
Add mime type detection. If mime type is not `image/*` throw not implemented  error. If PIL doesn't support image throw different error.
