### ISSUE TITLE
Set HWD from IIIF

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#56]
## Description
Retrieve the `info.json` for a resource, and add height, width, and duration properties to a Canvas or Content Resource object, allowing nulls

## Function name / Parameters / Return

Function name: `.set_hwd_from_iiif(url)`

Parameters: `url` - the IIIF Image API URL for the resource

Returns: `None`

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [ ] Collection
- [ ] Manifest
- [x] Canvas
- [ ] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [x] Content Resource - Image
- [x] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

## Considerations

This will introduce a new dependency for retrieving the `info.json` file, probably [requests](https://requests.readthedocs.io/en/latest/). Please discuss before adding.

The URL provided by the user might already be the full path to the `info.json` file, so the helper should check this and not add it if unnecessary,

For Canvas objects, if `height` is present, then `width` must also be set, and vice-versa (https://iiif.io/api/presentation/3.0/#height / https://iiif.io/api/presentation/3.0/#width), Therefore the helper must be type aware, and raise an error if one is set without the other when the target is a Canvas object

Since this helper will be making a request to an external HTTP(S) resource, it should be prepared to gracefully handle errors and 404s etc, raising them to the main library as appropriate.

**Comment by digitaldogsbody** [comment]
It occurs to me that this helper _could_ call the Set HWD helper #(54) once it has established the values, to minimise code duplication a little. This is something we could add after if we wanted, so not a hard requirement for the hackathon.

**Comment by rlskoeser** [comment]
@digitaldogsbody that seems logical, should I work on #54 first?
