### ISSUE TITLE
Documentation: How to use this library

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#6]

**Comment by rbturnbull** [comment]
Thanks for your work on this module. I'm keen to read these docs as they are written.

**Comment by mbennett-uoe** [comment]
Add how to write helper methods doc

**Comment by digitaldogsbody** [comment]
Helper methods: https://github.com/iiif-prezi/iiif-prezi3/blob/main/docs/write-helper-method.md

**Comment by glenrobson** [comment]
Agreed in last meeting this is done.
