### ISSUE TITLE
Get Reference

### ISSUE THREAD

**Issue by martimpassos** [iiif-prezi/iiif-prezi3#69]
## Description
This helper takes a `Manifest` and returns a `Reference` that points to it

## Function name / Parameters / Return

Function name: .get_reference()

Parameters: None

Returns: A `Reference` object

## Objects

- [ ] Base Object (all Prezi3 Classes)
- [ ] Collection
- [X] Manifest
- [ ] Canvas
- [ ] Range
- [ ] AnnotationCollection
- [ ] AnnotationPage
- [ ] Annotation
- [ ] Content Resource - Image
- [ ] Content Resource - Video
- [ ] Content Resource - Text
- [ ] Service
- [ ] Provider
- [ ] Other - please list below

**Comment by martimpassos** [comment]
get_reference? to_reference?

Or rather Reference.from_manifest(manifest)?

**Comment by glenrobson** [comment]
Done in:

https://github.com/iiif-prezi/iiif-prezi3/pull/81

Should be able to create a reference by doing manifest.to_reference
