### ISSUE TITLE
Documentation uses invalid notation for label langstring.

### ISSUE THREAD

**Issue by robcast** [iiif-prezi/iiif-prezi3#76]
The documentation e.g. https://github.com/iiif-prezi/iiif-prezi3/blob/main/docs/getting-started-using-iiifprezi3-without-helpermethods.md uses `label={'en': 'default label'}` but that doesn't work. It should be `label={'en': ['default label']}`

**Comment by giacomomarchioro** [comment]
You are right It Is based on a precipua version of the package when we did not fix this issue i can fix It
