### ISSUE TITLE
Add manifest to collection

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#8]

**Comment by glenrobson** [comment]
Maybe add a Manifest Reference to the schema to handle this.

**Comment by giacomomarchioro** [comment]
A working example can be produced using the modified JSON schema (see  https://github.com/IIIF/presentation-validator/pull/123)

```
from iiif_prezi3 import Collection,Refmanifest
col = Collection(id="https://test.com",type="Collection")
refman = Refmanifest(id="https://refman.com",type="Manifest",label={"en":"mylabel"}) 
col.items = []
col.items.append(refman)
col.json(exclude_unset=True)
```

The output is correct except for the label see issue https://github.com/iiif-prezi/iiif-prezi3/issues/11.

Possibly, the method could be encapsulated in a helper function e.g. `add_mannifest_to_collection`.

**Comment by giacomomarchioro** [comment]
I opened a new issue in the presentation-validator I think it should be discussed further: https://github.com/IIIF/presentation-validator/issues/128

**Comment by giacomomarchioro** [comment]
After https://github.com/IIIF/presentation-validator/pull/130 the reference class can be used to add a reference to a manifest inside a collection see the tutorial using an helper function here:
https://github.com/giacomomarchioro/iiif-prezi3/blob/main/tutorial.ipynb

**Comment by giacomomarchioro** [comment]
This pull request should fix the issue https://github.com/iiif-prezi/iiif-prezi3/pull/30

**Comment by digitaldogsbody** [comment]
Hackathon/Helper tickets: #37, #42
