### ISSUE TITLE
Update PyPi publish action

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#85]
The following warning showed up in the logs for the last action that made a release to PyPi:

>Warning:  You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

**Comment by glenrobson** [comment]
Looks like the latest is 1.5.1: https://github.com/pypa/gh-action-pypi-publish/releases/
