### ISSUE TITLE
Image info from file or IIIF

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi3#9]
Populate Image resource with info from either a file or IIIF info.json:

https://github.com/iiif-prezi/iiif-prezi/blob/e5956d5ab929ff8149a6429c6145790bb4bd59e5/iiif_prezi/factory_11.py#L822

Would require PIL if we are going to open images.

**Comment by digitaldogsbody** [comment]
Helper issue for hackathon: https://github.com/iiif-prezi/iiif-prezi3/issues/55
