### ISSUE TITLE
Automate Skeleton generation and changes

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#94]
Write a wrapper python script that generates the skeleton file using datamodel-codegen and then applies any necessary changes,

Changes so far:
* `LngString` fix
* Rename `_id` and `_type` to `id` and `type` in `ServiceItem1`

**Comment by glenrobson** [comment]
Mike looking at adding this with a Python script.

**Comment by digitaldogsbody** [comment]
Added with #141
